slotIntervalInSeconds: 300

emu_measurement_powerQuantPU: 200
smartmeter_powerQuantPU: 200
emu_control_powerQuantPU: 200
minPowerDemandInW: 0
maxPowerDemandInW: 2200
batteryRatedPower: 6000

batteryRatedCapacityInAh: 30
bat_power_scaling_factor: 5
batteryNominalVoltage: 48

cell_SOC_high: 0.9
cell_SOC_low: 0.1
cell_SOC_init: 0.1
cell_voltage_high: 4.2
cell_voltage_low: 2.5
cell_nominalVoltage: 4
converterEfficiency: 95
cell_1C_capacityInAh: 1.8048

allowedRelativeCapacityChange: 20
limit_y_range_to_x_range: 1

emulator: 'comsol'
sample_num: 50
deglifePartitions_num: 1
driveToSOH_timeAccelerationFactor: 100
driveToSOC_timeAccelerationFactor: 1
driveToSOC_timePeriodScaleFactor: 1
driveToSOC_attempts_max: 100

capacityCostPerkWh: 130

hypothesisStatesPerAppliance: [2]
costPerApplianceDetection_emu : [1]
rewardPerApplianceDetection_adv : [1]
homogeneous_reward : 0
reward_amplifying_factor: 1
applianceGroup1Threshold: [10]

applianceGroupsNum: 1
hypothesisStatesNum: 2

applianceGroup1: ['stove','oven']


controlStartTime: 10
controlEndTime: 14

batteryLevelsNum: 5

paramsPrecision: 1e-6
beliefSpacePrecision_adv: 1e-3
minLikelihoodFilter: 1e-4

OSG_max_cache_size: 1e4
dataset: 'kth_lil'
dataType: 'real'
data_training_validation_ratio: 0.6

numTrainHorizons: 5000
exploration_epsilon: 0.05
noise_epsilon: 0.05
TargetSmoothFactor_C: 0.1
TargetSmoothFactor_Ac: 0.01

numEvalHorizons: 2000

learning_rate_Ac: 0.001
learning_rate_C: 0.001
discountFactor: 0.99

GradientDecayFactor_Ac: 0.9
SquaredGradientDecayFactor_Ac: 0.9990
Epsilon_adam_Ac: 1e-8

GradientDecayFactor_C: 0.9
SquaredGradientDecayFactor_C: 0.9990
Epsilon_adam_C: 1e-8

actor_net_hidden_layers : 6
actor_net_hidden_layer_neurons_ratio: 0.3
critic_net_hidden_layers : 10
critic_net_hidden_layer_neurons_ratio_obs: 0.8
critic_net_hidden_layer_neurons_ratio_act: 0.5

MiniBatchSize: 64
InMemoryUpdateInterval: 0
ReplayBufferLength: 1e4
penalty_factor: 0

logistic_param_limit: 10
y_num_for_exploration: 4
num_rand_adv_strats_for_exploration: 128


discountFactor_DBS: 0.9
max_valueFnIterations: 25
beliefSpacePrecision_EMU_subopt_DBS: 0.2
value_iter_conv_threshold: 1e-1

NC: 1
RL_DeterministicActorCriticAgent_RD: 1
subopt_DBS_FDC_UA: 1