# Test cases
NC: 1
inst_opt_FDC: 1
opt_det_subpolicy_FDC: 1
subopt_det_subpolicy_FDC: 1
subopt_DBS_FDC: 1
subopt_DBS_FDC_UA: 1
best_effort_moderation: 1
differential_privacy: 1
AMDPG: 1

# Discretization of measurements
slotIntervalInSeconds: 900
emu_measurement_powerQuantPU: 100
smartmeter_powerQuantPU: 100
emu_control_powerQuantPU: 100
minPowerDemandInW: 0
maxPowerDemandInW: 100
limit_y_range_to_x_range: 1

# Battery
batteryRatedPower: 200
batteryRatedCapacityInAh: 1.1
bat_power_scaling_factor: 2
batteryNominalVoltage: 48
cell_SOC_high: 0.9
cell_SOC_low: 0.1
cell_SOC_init: 0.1
cell_voltage_high: 4.2
cell_voltage_low: 2.5
cell_nominalVoltage: 4
converterEfficiency: 95
cell_1C_capacityInAh: 1.8048
allowedRelativeCapacityChange: 20
capacityCostPerkWh: 130
cell_mean_power_loss_param: 320.74
beta_max_var: 0.2
min_alpha_plus_beta: 0.1
ess_extreme_prob_fact: 0.1
ess_extreme_prob_range_num: 2
batteryLevelsNum_paramapprox: 1

# Hypothesis State 
homogeneous_reward : 0
applianceGroup1: ['toy']
applianceGroupsNum: 1
hypothesisStatesPerAppliance: [2]
hypothesisStatesNum: 2
costPerApplianceDetection_emu : [1]
rewardPerApplianceDetection_adv : [1]
reward_amplifying_factor: 1
applianceGroup1Threshold: [10]
P_XgH_h1_param: 0.05
P_XgH_h2_param: 0.85

# General Controller
controlStartTime: 0
controlEndTime: 24
paramsPrecision: 1e-6
beliefSpacePrecision_adv: 1e-3
minLikelihoodFilter: 1e-4

# Common MDP controllers
discountFactor_MDP: 0.9

# MDP controllers with discrete belief space
max_valueFnIterations: 300
beliefSpacePrecision_EMU_subopt_DBS: 0.2
value_iter_conv_threshold: 1e-1

# MDP controllers with deterministic subpolicy
doPruning: 0
max_num_gamma_vectors: 1e6
minDet: 1e-5
gamma_vec_conv_threshold: 1e-6
max_num_EMUsubpolicies_opt: 12
max_num_EMUsubpolicies_subopt: 12

# MDP controllers with instantaneous optimal subpolicy
max_cache_size: 1e4

# Reinforcement learning
with_bem_initialized_actor: 0
with_controller_reward: 0
with_mean_reward: 1
numTrainHorizons: 4000
discountFactor_RL: 0.99
noise_epsilon: 0.03
noise_sd: 0.05
MiniBatchSize: 64
ReplayBufferLength: 1e4
logistic_param_limit: 10
actor_net_hidden_layers : 3
actor_net_hidden_layer_neurons_ratio_obs: 0.5
actor_net_hidden_layer_neurons_ratio_act: 0.5
GradientDecayFactor_Ac: 0.9
SquaredGradientDecayFactor_Ac: 0.9990
Epsilon_adam_Ac: 1e-8
critic_net_hidden_layers : 3
critic_net_hidden_layer_neurons_ratio_obs: 0.5
critic_net_hidden_layer_neurons_ratio_act: 0.5
GradientDecayFactor_C: 0.9
SquaredGradientDecayFactor_C: 0.9990
Epsilon_adam_C: 1e-8
learning_rate_Ac: 0.001
learning_rate_C: 0.001
TargetSmoothFactor_Ac: 0.001
TargetSmoothFactor_C: 0.1

# AMDPG
with_a_nncells: 1
exploration_epsilon: 0.03
y_num_for_exploration: 1
num_rand_adv_strats_for_exploration: 4